gnatyshkoProj/src/Locators
gnatyshkoProj/src/TestCases

2 files were added for hometask

overAll 2 files were added

---

zavertailoProj/src/Locators
zavertailoProj/src/TestCases

HW_1_Locators

---

bondarenkoProj/src/Locators
bondarenkoProj/src/TestCases

Привіт, Тарасе!
Чи можу я обрати для екзаменаційного проекту тестове середовище CRM системи Salesforce? 
Це мій робочий проект :)

Bondarenko homework 12 27

---

gnatyshkoProj/src/Locators
gnatyshkoProj/src/TestCases

- TestCases: 5 test cases created for testing https://qa-complex-app-for-testing.herokuapp.com/
- Locators: locators added as acc to the used elements in TestCases

Homework #1:

---

zherebtsovaProj/pom.xml
zherebtsovaProj/src/test/java/LoginTest/LoginTest1.java

My first login test

---

moiseievaProj/src/Locators
moiseievaProj/src/TestCase

moiseieva - hw 1

---

siforovProj/pom.xml
siforovProj/src/log4j.properties
siforovProj/src/main/java/pages/HomePage.java
siforovProj/src/main/java/pages/LoginPage.java
siforovProj/src/main/java/pages/ParentPage.java
siforovProj/src/test/java/LoginTest/LoginTestWithPageObject.java
siforovProj/src/test/java/baseTest/BaseTest.java

Automation test framework refactoring

Automation Framework refactoring v1

---

gnatyshkoProj/pom.xml
gnatyshkoProj/src/log4j.properties
gnatyshkoProj/src/main/java/pages/HomePage.java
gnatyshkoProj/src/main/java/pages/LoginPage.java
gnatyshkoProj/src/main/java/pages/ParentPage.java
gnatyshkoProj/src/test/java/baseTest/BaseTest.java
gnatyshkoProj/src/test/java/loginTests/LoginTestWithPageObject.java

test with PageObject pattern

---

gnatyshkoProj/src/main/java/pages/LoginPage.java
gnatyshkoProj/src/test/java/loginTests/LoginTest.java
gnatyshkoProj/src/test/java/loginTests/LoginTestWithPageObject.java

invalidLogin test with and without PageObject Pattern

homework invalid login

---

bondarenkoProj/src/test/java/loginTests/LoginTest.java
bondarenkoProj/src/test/java/loginTests/LoginTestWithPageObject.java

Привіт!
Тарасе, а це ок, що мої тести виконуються знизу вверх, якщо запустити їх всі? Тобто, у мене першим тестом в коді іде тест validLogin, другим - inValidLogin, а виконується першим - inValidLogin, а другим - validLogin.
Дякую

Second and third homeworks

---

moiseievaProj/src/main/java/libs/TestData.java
moiseievaProj/src/main/java/pages/HomePage.java
moiseievaProj/src/main/java/pages/LoginPage.java
moiseievaProj/src/main/java/pages/ParentPage.java
moiseievaProj/src/test/java/postsTests/CreatePostTest.java

methods were added in ParenPage

Moiseieva 01 04

---

siforovProj/src/main/java/libs/TestData.java
siforovProj/src/main/java/pages/HomePage.java
siforovProj/src/main/java/pages/LoginPage.java
siforovProj/src/main/java/pages/ParentPage.java
siforovProj/src/test/java/postsTests/CreatePostTest.java

PageObject + Paje Factory learning. Tests refactoring

PageObject + Paje Factory learning

---

kolbasinProj/src/Locators
kolbasinProj/src/TestCases

еще не добавил в некоторых местах локаторы. если не забуду -- добавлю. и некоторые кнопки в кейсах забыл добавить((

HW Locators and TestCases

---

siforovProj/src/main/java/libs/TestData.java
siforovProj/src/main/java/pages/HomePage.java
siforovProj/src/main/java/pages/LoginPage.java
siforovProj/src/main/java/pages/ParentPage.java
siforovProj/src/main/java/pages/ProfilePage.java
siforovProj/src/test/java/LoginTest/ChatTest.java
siforovProj/src/test/java/LoginTest/LoginTestWithPageObject.java
siforovProj/src/test/java/LoginTest/ProfileTest.java
siforovProj/src/test/java/LoginTest/SearchTest.java
siforovProj/src/test/java/LoginTest/SingUpTest.java
siforovProj/src/test/java/baseTest/BaseTest.java

All 3 homeworks have been completed

Siforov all homeworks 05 01 2022

---

latsynskyiProj/src/test/java/loginTests/LoginTests.java

в цей реквест також попали фікси по дз з локаторами і тесткейсами

Latsynskyi 30 12 hw2

---

gnatyshkoProj/src/main/java/libs/TestData.java
gnatyshkoProj/src/main/java/pages/HomePage.java
gnatyshkoProj/src/main/java/pages/LoginPage.java
gnatyshkoProj/src/main/java/pages/ParentPage.java
gnatyshkoProj/src/test/java/loginTests/LoginTest.java
gnatyshkoProj/src/test/java/loginTests/LoginTestWithPageObject.java
gnatyshkoProj/src/test/java/signUpTests/SignUpTest.java

-SignUpTest class added with invalidSignUp method
-locators for signUp added to LoginPage
-invalid signUp data added to TestData
-refactoring of errorMessage locator as acc to the latest fix

gnatyshkoProj-hw-invalid-registry(signUp)

---

siforovProj/src/main/java/pages/CreatePostPage.java
siforovProj/src/main/java/pages/ParentPage.java
siforovProj/src/main/java/pages/PostPage.java
siforovProj/src/test/java/postsTests/CreatePostTest.java

Homework 4. The custom select option.

Siforov 12 01 2022 hw

---

zherebtsovaProj/pom.xml
zherebtsovaProj/src/Locators
zherebtsovaProj/src/TestCases
zherebtsovaProj/src/log4j.properties
zherebtsovaProj/src/main/java/libs/TestData.java
zherebtsovaProj/src/main/java/libs/Util.java
zherebtsovaProj/src/main/java/pages/CreatePostPage.java
zherebtsovaProj/src/main/java/pages/HomePage.java
zherebtsovaProj/src/main/java/pages/LoginPage.java
zherebtsovaProj/src/main/java/pages/MyProfilePage.java
zherebtsovaProj/src/main/java/pages/ParentPage.java
zherebtsovaProj/src/main/java/pages/ParentPageWithHeader.java
zherebtsovaProj/src/main/java/pages/PostPage.java
zherebtsovaProj/src/test/java/BaseTest/BaseTest.java
zherebtsovaProj/src/test/java/LoginTest/CreatePostTest.java
zherebtsovaProj/src/test/java/LoginTest/TestWithOldCode.java
zherebtsovaProj/src/test/java/LoginTest/TestWithPO.java
zherebtsovaProj/src/test/java/LoginTest/TestWithPageObject.java

13.01 zherebtsova

---

siforovProj/src/main/java/pages/CreatePostPage.java
siforovProj/src/main/java/pages/HomePage.java
siforovProj/src/main/java/pages/LoginPage.java
siforovProj/src/main/java/pages/ParentPage.java
siforovProj/src/main/java/pages/ParentPageWithHeader.java
siforovProj/src/main/java/pages/PostPage.java
siforovProj/src/main/java/pages/ProfilePage.java
siforovProj/src/test/java/postsTests/CreatePostTest.java

Lesson 25-01-2022. Test refactor

Lesson 25-01-2022. Test refactor

---

zherebtsovaProj/src/main/java/pages/CreatePostPage.java
zherebtsovaProj/src/main/java/pages/HomePage.java
zherebtsovaProj/src/main/java/pages/LoginPage.java
zherebtsovaProj/src/main/java/pages/MyProfilePage.java
zherebtsovaProj/src/main/java/pages/ParentPage.java
zherebtsovaProj/src/main/java/pages/ParentPageWithHeader.java
zherebtsovaProj/src/main/java/pages/PostPage.java
zherebtsovaProj/src/test/java/LoginTest/CreatePostTest.java

25.01 lesson

---

pom.xml
zherebtsovaProj/pom.xml
zherebtsovaProj/src/main/java/pages/HomePage.java
zherebtsovaProj/src/main/java/pages/LoginPage.java
zherebtsovaProj/src/main/java/pages/MyProfilePage.java
zherebtsovaProj/src/main/java/pages/PostPage.java
zherebtsovaProj/src/test/java/registrationTestWithPageObject/registrationTestWithPageObject.java

27.01 zherebtsova 1

---

siforovProj/pom.xml
siforovProj/src/main/java/pages/ParentPage.java
siforovProj/src/test/java/baseTest/BaseTest.java
siforovProj/src/test/java/registrationTests/RegistrationTestsSecondVersion.java

Siforov 01 02 2022

---

siforovProj/src/main/java/libs/TestData.java
siforovProj/src/main/java/pages/CreatePostPage.java
siforovProj/src/main/java/pages/EditPostPage.java
siforovProj/src/main/java/pages/ParentPageWithHeader.java
siforovProj/src/main/java/pages/PostPage.java
siforovProj/src/main/java/pages/ProfilePage.java
siforovProj/src/test/java/LoginTest/EditPostTest.java
siforovProj/src/test/java/postsTests/CreatePostTest.java

Home work with Select and Home work with Edit Post

Siforov hw 31 01 2022

---

gnatyshkoProj/pom.xml
gnatyshkoProj/src/main/java/pages/HomePage.java
gnatyshkoProj/src/main/java/pages/LoginPage.java
gnatyshkoProj/src/test/java/baseTest/BaseTest.java
gnatyshkoProj/src/test/java/loginTests/LoginTestWithPageObject.java

gnatyshkoProj-02-15

---

siforovProj/src/main/java/api/PrivateBankEndpoints.java
siforovProj/src/main/java/api/PrivateCurrencyCourseDTO.java
siforovProj/src/test/java/apiTests/PrivateBankApiTest.java
siforovProj/src/test/java/apiTests/PrivateCurrencyCourseDTO.java

homeWorkAPI private Bank test

---

gnatyshkoProj/pom.xml
gnatyshkoProj/src/main/java/api/herokuapp/ApiHelper.java
gnatyshkoProj/src/main/java/api/herokuapp/AuthorDTO.java
gnatyshkoProj/src/main/java/api/herokuapp/EndPoints.java
gnatyshkoProj/src/main/java/api/herokuapp/PostDTO.java
gnatyshkoProj/src/main/java/api/privatbank/ApiHelperPrivatBank.java
gnatyshkoProj/src/main/java/api/privatbank/Currency.java
gnatyshkoProj/src/main/java/api/privatbank/ExchangeRateDTO.java
gnatyshkoProj/src/main/java/api/privatbank/PrivatEndPoins.java
gnatyshkoProj/src/main/java/libs/DriverHelper.java
gnatyshkoProj/src/main/java/pages/LoginPage.java
gnatyshkoProj/src/main/java/resources/response.json
gnatyshkoProj/src/main/java/resources/responsePrivatBank.json
gnatyshkoProj/src/main/java/resources/simplelogger.properties
gnatyshkoProj/src/test/java/RunCucumberTest.java
gnatyshkoProj/src/test/java/StepDefinitions/Hooks.java
gnatyshkoProj/src/test/java/StepDefinitions/LoginPage_StepDefinition.java
gnatyshkoProj/src/test/java/apiTests/CreatePostByApiTests.java
gnatyshkoProj/src/test/java/apiTests/HerokuappApiTests.java
gnatyshkoProj/src/test/java/apiTests/PrivatApiTests.java
gnatyshkoProj/src/test/resources/loginTests/login.feature

All classwork and homework is added in this pr

added all api test course

---

siforovProj/src/main/java/api/ApiHelper.java
siforovProj/src/main/java/libs/TestData.java
siforovProj/src/main/java/pages/HomePage.java
siforovProj/src/main/java/pages/ProfilePage.java
siforovProj/src/test/java/StepDefinitions/API_StepDefinition.java
siforovProj/src/test/java/StepDefinitions/HomePage_StepDefinition.java
siforovProj/src/test/java/StepDefinitions/Hooks.java
siforovProj/src/test/java/StepDefinitions/ProfilePage_StepDefinition.java
siforovProj/src/test/resources/post/post.feature

Mixed API + Cucumber test

---

harmashProj/src/test/java/StepDefinitions/LoginPage_StepDefinition.java
harmashProj/src/test/resources/loginTests/login.feature

Login with valid Login

---

gnatyshkoProj/src/main/java/api/privatbank/ApiHelperPrivatBank.java
gnatyshkoProj/src/main/java/api/privatbank/PrivatEndPoins.java
gnatyshkoProj/src/main/java/api/privatbank/PrivatEndPoints.java
gnatyshkoProj/src/main/java/libs/TestData.java
gnatyshkoProj/src/main/java/pages/ParentPage.java
gnatyshkoProj/src/main/java/pages/privatbank/ParentPage.java
gnatyshkoProj/src/main/java/pages/privatbank/PrivatbankPage.java
gnatyshkoProj/src/test/java/StepDefinitions/LoginPage_StepDefinition.java
gnatyshkoProj/src/test/java/StepDefinitions/Privatbank_StepDefinition.java
gnatyshkoProj/src/test/java/apiTests/PrivatApiTests.java
gnatyshkoProj/src/test/resources/privatBankTests/currency.feature

gnatyshkoProj-exam-project

---

bondarenkoProj/src/main/java/api/privatBank/ExchangeRateDTO.java
bondarenkoProj/src/main/java/api/privatBank/PrivatBankApiHelper.java
bondarenkoProj/src/main/java/pages/PrivatBankHomePage.java
bondarenkoProj/src/test/java/StepDefinitions/PrivatBankAPI_StepDefinition.java
bondarenkoProj/src/test/java/StepDefinitions/PrivatBankHomePage_StepDefinition.java
bondarenkoProj/src/test/java/apiTests/ApiPrivatBankTest.java
bondarenkoProj/src/test/resources/privatBankExchangeRatesTests/privatBankExchangeRates.feature

Привіт, Тарасе!
Надсилаю тобі ще недороблену екзаменаційну роботу по API, бо маю питання:
Чомусь не можу зробити перевірку за допомогою Assert в public class PrivatBankApiHelper. Пише, що required type boolean, а в мене void. Закоментила цей код, щоб не видавало помилки)) Допоможи, будь ласка)
Можливо, ти ще щось знайдеш те, що неправильно)
Дякую.

Exam_API project
